### ISSUE TITLE
multi user calendar

### ISSUE THREAD

**Issue by fouadkada** [LordEidi/fennel#14]
hey,

I wanna ask about whether fennel is the right solution to the problem I am trying to solve.

I am building a multi user mobile app where the users are supposed to have a "calendar" each.
the mobile app will display the calendar of the user as well as be able to edit his/her calendar.

when a user needs to schedule an appointment on another user's calendar, the scheduling will be made from the backend not from the mobile application directly.

I am wondering if fennel has this capability.

**Comment by LordEidi** [comment]
If you manage both, the server and client, I'd suggest to do something proprietary with your own protocol. But that is just me.

If you need to use CalDAV, then Fennel could do the trick. The data is stored in whatever database you configure. Which means that you can manipulate the data within the database without the use of Fennel.  But I haven't tried multi user yet and the authorisation part of fennel is nearly non-existent. You would need to invest into that...

**Comment by fouadkada** [comment]
I already checked the authentication code in fennel and figured out how to add authentication by calling some authentication API. (i can create a pull request if you are interested)

the simple question now is, can i create a separate calendar for each user that only he/she can access?

**Comment by LordEidi** [comment]
Yes, I am interested. Especially when things come to authorisation and enforcement of some kind of ACL when accessing the resources.

And yes, you can create different calendars for different users. As you can see in server.js:

```
crossroads.addRoute('/p/:params*:', onHitPrincipal);
crossroads.addRoute('/cal/:username:/:cal:/:params*:', onHitCalendar);
crossroads.addRoute('/card/:username:/:card:/:params*:', onHitCard);
```
All the URLs contain the specific username. All records in the database contain that information.

What fennel currently does is some global enforcement where it checks if you should get access on an application level.

What fennel currently does not make is to enforce authorisation rules when accessing records. I am a huge fan of https://shiro.apache.org/ but I never found the time to integrate a similar concept to fennel. I would love to have something like that: https://shiro.apache.org/permissions.html

**Comment by LordEidi** [comment]
I just uploaded some changes which add authorisation to fennel. Have a look at config.js -> authorisation. That could probably help with your problem...
