### ISSUE TITLE
Change license from GPL to LGPL

### ISSUE THREAD

**Issue by mwalkerwells** [LordEidi/fennel#16]
Hello! I'd like to use Fennel as a library on a personal closed source project. Would you be open to changing the license to make that possible?

"GENERAL PUBLIC LICENSE" —> "LESSER GENERAL PUBLIC LICENSE"

> If a library is released under the GPL (not the LGPL), does that mean that any software which uses it has to be under the GPL or a GPL-compatible license? (#IfLibraryIsGPL)
Yes, because the program actually links to the library. As such, the terms of the GPL apply to the entire combination. The software modules that link with the library may be under various GPL compatible licenses, but the work as a whole must be licensed under the GPL.

https://www.gnu.org/licenses/gpl-faq.en.html#IfLibraryIsGPL

**Comment by LordEidi** [comment]
If it is a personal project, why the need for a change?

**Comment by mwalkerwells** [comment]
While I'd like to in the future, I'm not ready to commit to open sourcing everything I write. IRRC, if one node in the dependency graph is under GPL, all other nodes must conform.

**Comment by LordEidi** [comment]
That's not what I meant. Have a look at this link:

https://www.gnu.org/licenses/gpl-faq.html#GPLRequireSourcePostedPublic

If yours is as you say a personal project (as I understand as for you only and not for public release) why worry?

**Comment by mwalkerwells** [comment]
Sorry, was a bit confused. It seems GPL will work for my use case.
