### ISSUE TITLE
Calendar

### ISSUE THREAD

**Issue by ubwhole** [LordEidi/fennel#17]
I want to add a calendar and contact storage to my website.  I want my users to be able to add and remove calendar and contact items.  When it is determined that a user has to achieve a goal, I want our system to update their calendar with tasks/events related to their goal.  Also, to have calendars shared with team members.

I want to use Fennel mainly because it is written in Javascript.  But I am not sure what are the features that are already implemented.  I am not sure what Lightweight means in the description.  I understand Fennel is just the server and I need to find a client solution.  Can you suggest a browser library that can be used to interact with Fennel?  Can you advise me if Fennel is a potential fit for what I want to do?

Thanks

**Comment by LordEidi** [comment]
Fennel is an implementation of CalDAV and CardDAV, where you can use whatever Card- and CalDAV client there is and you like.

If you keep things web/html only and don't need any xDAV, Fennel is probably not what you are looking for. Why don't you just store everything you need in a database in a structure which suits your needs with an http API which suits you. Much simpler than to go through the hassle of Card/CalDAV.

**Comment by ubwhole** [comment]
Right now I am learning what is Cal/CardDAV and what are the different existing implementations.  I believe I do need xDAV e.g. will need iCal to import/export calendars, multiple users modifying a calendar.  I assumed this is what Fennel provides.  Correct?
