### ISSUE TITLE
CalDAV sync is not working in android devices

### ISSUE THREAD

**Issue by sudha53633** [LordEidi/fennel#2]
Hi LordEidi,

I'm honestly appreciating for your work on CalDAV protocol implementation for syncing of calendar events. I've used fennel, it's fantastically working in my IPhone devices. But it's not syncing for Android devices. Would you please let me know, how can i move forward to work on Android devices.

Thanks,
sudha53633

**Comment by tobiasmuecksch** [comment]
Why is this issue still open?

**Comment by LordEidi** [comment]
Nobody probably closed this :)
