### ISSUE TITLE
DAVdroid fails to setup new account

### ISSUE THREAD

**Issue by kewllife** [LordEidi/fennel#4]
Compiled DAVdroid from sources and tried to add a new account to connect to Fennel. It authenticates correctly, but then I get this error on the device.

DAVDroid Error:

```
Missing capabilities: Invalid DAV response: Couldn't parse Multi-Status response on REPORT multi-get
```

Fennel Log:

```
[2014-11-03 14:38:00.442] [DEBUG] fennelapp - logger loaded
DEPRECATION WARNING: The logging-option should be either a function or false. Default: console.log
[2014-11-03 14:38:01.311] [INFO] fennelapp - Server running at http://127.0.0.1:8888/
[2014-11-03 14:38:01.384] [INFO] fennelapp - Database structure updated
[2014-11-03 14:38:13.200] [DEBUG] fennelapp - Login process started for user: user
[2014-11-03 14:38:13.200] [DEBUG] fennelapp - Authenticating user with htaccess method.
[2014-11-03 14:38:13.200] [DEBUG] fennelapp - Read line from htaccess file: user:[passwd1]
[2014-11-03 14:38:13.203] [DEBUG] fennelapp - Read line from htaccess file: user:[passwd2]
[2014-11-03 14:38:13.203] [INFO] fennelapp - User logged in: user
[2014-11-03 14:38:13.203] [DEBUG] fennelapp - Method: PROPFIND, URL: /.well-known/carddav
[2014-11-03 14:38:13.208] [DEBUG] fennelapp - Called .well-known URL for carddav. Redirecting to /p/
[2014-11-03 14:38:13.471] [DEBUG] fennelapp - Login process started for user: user
[2014-11-03 14:38:13.471] [DEBUG] fennelapp - Authenticating user with htaccess method.
[2014-11-03 14:38:13.472] [DEBUG] fennelapp - Read line from htaccess file: user:[passwd1]
[2014-11-03 14:38:13.472] [DEBUG] fennelapp - Read line from htaccess file: user:[passwd2]
[2014-11-03 14:38:13.472] [INFO] fennelapp - User logged in: user
[2014-11-03 14:38:13.472] [DEBUG] fennelapp - Method: PROPFIND, URL: /p/
[2014-11-03 14:38:13.473] [DEBUG] fennelapp - principal.propfind called
[2014-11-03 14:38:13.697] [DEBUG] fennelapp - Login process started for user: user
[2014-11-03 14:38:13.698] [DEBUG] fennelapp - Authenticating user with htaccess method.
[2014-11-03 14:38:13.698] [DEBUG] fennelapp - Read line from htaccess file: user:[passwd1]
[2014-11-03 14:38:13.698] [DEBUG] fennelapp - Read line from htaccess file: user:[passwd2]
[2014-11-03 14:38:13.698] [INFO] fennelapp - User logged in: user
[2014-11-03 14:38:13.698] [DEBUG] fennelapp - Method: PROPFIND, URL: /
[2014-11-03 14:38:13.699] [DEBUG] fennelapp - calendar.propfind called
[2014-11-03 14:38:14.045] [DEBUG] fennelapp - Login process started for user: user
[2014-11-03 14:38:14.045] [DEBUG] fennelapp - Authenticating user with htaccess method.
[2014-11-03 14:38:14.046] [DEBUG] fennelapp - Read line from htaccess file: user:[passwd1]
[2014-11-03 14:38:14.046] [DEBUG] fennelapp - Read line from htaccess file: user:[passwd2]
[2014-11-03 14:38:14.046] [INFO] fennelapp - User logged in: user
[2014-11-03 14:38:14.046] [DEBUG] fennelapp - Method: PROPFIND, URL: /p/user/
[2014-11-03 14:38:14.046] [DEBUG] fennelapp - principal.propfind called
```

Can you make any sense of this? If you can point me towards a file and I can try to work on this issue.

Thanks

**Comment by marller2013** [comment]
I was also meeting this problem.Something happened that cause the URL wrong.Is there somebody  solving it?
e.g

06-08 23:26:48.959: I/Choreographer(6027): Skipped 32 frames!  The application may be doing too much work on its main thread.
06-08 23:26:49.099: I/Choreographer(6027): Skipped 34 frames!  The application may be doing too much work on its main thread.
06-08 23:26:49.199: W/ActivityThread(6027): ClassLoader.loadClass: The class loader returned by Thread.getContextClassLoader() may fail for processes that host multiple applications. You should explicitly specify a context class loader. For example: Thread.setContextClassLoader(getClass().getClassLoader());
06-08 23:26:53.449: D/dalvikvm(6027): GC_FOR_ALLOC freed 266K, 8% free 4390K/4732K, paused 69ms, total 70ms
06-08 23:26:53.459: V/davdroid.TlsSniSocketFactory(6027): Setting allowed TLS protocols: TLSv1, TLSv1.1, TLSv1.2
06-08 23:26:53.459: I/Choreographer(6027): Skipped 30 frames!  The application may be doing too much work on its main thread.
06-08 23:26:56.549: I/Choreographer(6027): Skipped 32 frames!  The application may be doing too much work on its main thread.
06-08 23:27:00.049: I/davdroid.ResourceFinder(6027): *** Starting CardDAV resource detection
06-08 23:27:00.049: D/davdroid.ResourceFinder(6027): Looking up SRV records for _carddavs._tcp.192.168.1.53
06-08 23:27:00.989: D/dalvikvm(6027): GC_FOR_ALLOC freed 209K, 6% free 4714K/5004K, paused 40ms, total 69ms
06-08 23:27:00.989: I/Choreographer(6027): Skipped 31 frames!  The application may be doing too much work on its main thread.
06-08 23:27:05.079: I/Choreographer(6027): Skipped 42 frames!  The application may be doing too much work on its main thread.
06-08 23:27:12.479: I/davdroid.ResourceFinder(6027): Looking up principal URL for service carddav; initial context: http://192.168.1.53:8080/caladmin/
06-08 23:27:12.679: D/davdroid.WebDavResource(6027): Using preemptive authentication (not compatible with Digest auth)
06-08 23:27:12.719: V/davdroid.URIUtils(6027): Normalized URL /.well-known/carddav -> /.well-known/carddav
06-08 23:27:12.779: I/dalvikvm(6027): Could not find method javax.xml.stream.XMLInputFactory.newInstance, referenced from method org.simpleframework.xml.stream.StreamProvider.<init>
06-08 23:27:12.779: W/dalvikvm(6027): VFY: unable to resolve static method 5460: Ljavax/xml/stream/XMLInputFactory;.newInstance ()Ljavax/xml/stream/XMLInputFactory;
06-08 23:27:12.779: D/dalvikvm(6027): VFY: replacing opcode 0x71 at 0x0003
06-08 23:27:12.789: W/dalvikvm(6027): VFY: unable to find class referenced in signature (Ljavax/xml/stream/XMLEventReader;)
06-08 23:27:12.789: W/dalvikvm(6027): VFY: unable to find class referenced in signature (Ljavax/xml/stream/XMLEventReader;)
06-08 23:27:12.789: I/dalvikvm(6027): Could not find method javax.xml.stream.XMLInputFactory.createXMLEventReader, referenced from method org.simpleframework.xml.stream.StreamProvider.provide
06-08 23:27:12.789: W/dalvikvm(6027): VFY: unable to resolve virtual method 5458: Ljavax/xml/stream/XMLInputFactory;.createXMLEventReader (Ljava/io/InputStream;)Ljavax/xml/stream/XMLEventReader;
06-08 23:27:12.789: D/dalvikvm(6027): VFY: replacing opcode 0x6e at 0x0002
06-08 23:27:12.789: I/dalvikvm(6027): Could not find method javax.xml.stream.XMLInputFactory.createXMLEventReader, referenced from method org.simpleframework.xml.stream.StreamProvider.provide
06-08 23:27:12.789: W/dalvikvm(6027): VFY: unable to resolve virtual method 5459: Ljavax/xml/stream/XMLInputFactory;.createXMLEventReader (Ljava/io/Reader;)Ljavax/xml/stream/XMLEventReader;
06-08 23:27:12.789: D/dalvikvm(6027): VFY: replacing opcode 0x6e at 0x0002
06-08 23:27:12.839: I/Choreographer(6027): Skipped 35 frames!  The application may be doing too much work on its main thread.
06-08 23:27:16.619: I/Choreographer(6027): Skipped 36 frames!  The application may be doing too much work on its main thread.
06-08 23:27:17.279: V/davdroid.URIUtils(6027): Normalized URL http://192.168.1.53:8080/ucarddav/ -> http://192.168.1.53:8080/ucarddav/
06-08 23:27:17.279: I/davdroid.WebDavResource(6027): Redirection on PROPFIND; trying again at new content URL: http://192.168.1.53:8080/ucarddav/
06-08 23:27:17.569: D/dalvikvm(6027): GC_FOR_ALLOC freed 480K, 11% free 4886K/5440K, paused 83ms, total 83ms
06-08 23:27:17.959: D/davdroid.ResourceFinder(6027): Well-known carddav service detection failed with HTTP error
06-08 23:27:17.959: D/davdroid.ResourceFinder(6027): at.bitfire.davdroid.webdav.HttpException: 500 Internal Server Error
06-08 23:27:17.959: D/davdroid.ResourceFinder(6027): 	at at.bitfire.davdroid.webdav.WebDavResource.checkResponse(WebDavResource.java:442)
06-08 23:27:17.959: D/davdroid.ResourceFinder(6027): 	at at.bitfire.davdroid.webdav.WebDavResource.checkResponse(WebDavResource.java:416)
06-08 23:27:17.959: D/davdroid.ResourceFinder(6027): 	at at.bitfire.davdroid.webdav.WebDavResource.propfind(WebDavResource.java:309)
06-08 23:27:17.959: D/davdroid.ResourceFinder(6027): 	at at.bitfire.davdroid.resource.DavResourceFinder.getCurrentUserPrincipal(DavResourceFinder.java:264)
06-08 23:27:17.959: D/davdroid.ResourceFinder(6027): 	at at.bitfire.davdroid.resource.DavResourceFinder.findResources(DavResourceFinder.java:62)
06-08 23:27:17.959: D/davdroid.ResourceFinder(6027): 	at at.bitfire.davdroid.ui.setup.QueryServerDialogFragment$ServerInfoLoader.loadInBackground(QueryServerDialogFragment.java:120)
06-08 23:27:17.959: D/davdroid.ResourceFinder(6027): 	at at.bitfire.davdroid.ui.setup.QueryServerDialogFragment$ServerInfoLoader.loadInBackground(QueryServerDialogFragment.java:1)
06-08 23:27:17.959: D/davdroid.ResourceFinder(6027): 	at android.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:312)
06-08 23:27:17.959: D/davdroid.ResourceFinder(6027): 	at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:69)
06-08 23:27:17.959: D/davdroid.ResourceFinder(6027): 	at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:57)
06-08 23:27:17.959: D/davdroid.ResourceFinder(6027): 	at android.os.AsyncTask$2.call(AsyncTask.java:288)
06-08 23:27:17.959: D/davdroid.ResourceFinder(6027): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
06-08 23:27:17.959: D/davdroid.ResourceFinder(6027): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
06-08 23:27:17.959: D/davdroid.ResourceFinder(6027): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
06-08 23:27:17.959: D/davdroid.ResourceFinder(6027): 	at java.lang.Thread.run(Thread.java:841)
06-08 23:27:17.969: D/davdroid.ResourceFinder(6027): Well-known service detection failed, trying initial context path http://192.168.1.53:8080/caladmin/

**Comment by LordEidi** [comment]
The client should first hit the .well-known URL or take the URL provided by fennel during hitting the root URL. 

That URL you have in your log there does not look as I would expect it. Principal URLs should be formated host/p/principal, as example.

What is it you tell your client to use as the base URL?

**Comment by marller2013** [comment]
Maybe there's something wrong with my own configuration .However,  the app which download from official site communicate with the server perfectly.When I switch the app  I compiled,it's had a "time out".It's to be sure,after
I compiled the droiddav app code，and connected Fruux which given by droiddav official site,thers's nothing wrong.
When I debug it,I  detected  it get caldav protocol.But where is the "CardDAV"? Should it auto-detected?
----- 原始邮件 -----
发件人：LordEidi <notifications@github.com>
收件人：LordEidi/fennel <fennel@noreply.github.com>
抄送人：marller2013 <marller@sina.com>
主题：Re: [fennel] DAVdroid fails to setup new account (#4)
日期：2015年06月26日 22点01分

The client should first hit the .well-known URL or take the URL provided by fennel during hitting the root URL. 

That URL you have in your log there does not look as I would expect it. Principal URLs should be formated host/p/principal, as example.

What is it you tell your client to use as the base URL?

&mdash;

**Comment by LordEidi** [comment]
The CardDAV part is on the /card/ URI. But your client should be able to find that on its own.
