### ISSUE TITLE
Problems installing on Ubuntu

### ISSUE THREAD

**Issue by brettz9** [LordEidi/fennel#7]
Hi,

Upon attempting an npm install of fennel@beta on a machine running 
Ubuntu 14.04 , I get the following message:

     > sqlite3@2.1.19 install
    /root/fennel/node_modules/fennel/node_modules/sequelize-sqlite/node_modules/sqlite3
     > node build.js

    sh: 1: node: not found
    npm WARN This failure might be due to the use of legacy binary "node"
    npm WARN For further explanations, please read
    /usr/share/doc/nodejs/README.Debian

That README file indicates:

    The upstream name for the Node.js interpreter command is "node".
    In Debian the interpreter command has been changed to "nodejs".

    This was done to prevent a namespace collision: other commands use
    the same name in their upstreams, such as ax25-node from the "node"
    package.

    Scripts calling Node.js as a shell command must be changed to instead
    use the "nodejs" command.

Do you have any idea how to resolve this so that it will install 
properly on my machine? I'm quite new to Linux...

Thanks and best wishes,
Brett

**Comment by vitalyster** [comment]
apt-get install nodejs-legacy

**Comment by brettz9** [comment]
Awesome, thank you!--no errors installing this time...
