### ISSUE TITLE
Authification over  Database

### ISSUE THREAD

**Issue by genofire** [LordEidi/fennel#8]
At first thank you for using sequelize (so i could use mysql and postgresql).
Is it possbile to make the Authentification over this Database?

**Comment by LordEidi** [comment]
That should not be much of a problem. Have a look at libs/authentication.js. Basically you need to do your stuff and then call the callback method with true/false.

If we find a clever mechanism to configure that db authentication method, I'd add it to fennel for everybody to use.

**Comment by genofire** [comment]
Ah nice :)
your code is very simple and clear.
(it think about to rewrite it to the infrastructur of us, based on yours)

**Comment by genofire** [comment]
you could closed it if you do not want to implement it.
(i will fork it if i need)

**Comment by LordEidi** [comment]
Just send me your changes and I will add them to Fennel.

**Comment by genofire** [comment]
Nothing developed at the moment :( (no time, sry) - maybe in sommer. no promise.
